### ISSUE TITLE
Accessing team folders

### ISSUE THREAD

**Issue by hello-world-dot-c** [dropbox/dbxcli#203]
I have a Dropbox business account that has personal space and team space. When I access the account with dbxcli, I only see my personal space. Is there a way to access the shared team space as well?

**Comment by lukastvrdy** [comment]
@hello-world-dot-c have you solved the issue? I have the same problem.

**Comment by hello-world-dot-c** [comment]
No, I gave up on it.

**Comment by jeff-eyeq** [comment]
Just voting "me too"

**Comment by neon-ninja** [comment]
Hi - https://github.com/dropbox/dbxcli/pull/217 should fix this. While waiting for this to be merged, here's a prebuilt linux binary - https://github.com/UoA-eResearch/dbxcli/releases/tag/v3.0.1

**Comment by AndreyVMarkelov** [comment]
Fixed on `master`.

Team-space/member file access is now supported through the team-access login flow:

    dbxcli login team-access
    dbxcli --as-member dbmid:<team-member-id> ls /

Use `team-manage` credentials for team administration commands such as listing members:

    dbxcli login team-manage
    dbxcli team list-members

I also manually verified `--as-member dbmid:... ls`, upload, delete, and permanent delete against a real Dropbox Business member account. Closing this as fixed.

**Comment by neon-ninja** [comment]
@AndreyVMarkelov that only works for team admins to view other team members personal folders - https://github.com/dropbox/dbxcli/pull/217 would work for non-admins as well, and allows access to team folders

**Comment by AndreyVMarkelov** [comment]
Thanks, you’re right. The current fix covers team-access delegation with `--as-member`, but it does not fully solve team-space/team-folder access because we are not setting `Dropbox-API-Path-Root`.

PR #217 points in the right direction. I’ll treat #203 as partially fixed and follow up with path-root support, preferably using the SDK’s `Config.PathRoot` / `WithRoot` support rather than hand-building headers.

**Comment by neon-ninja** [comment]
@AndreyVMarkelov I've updated https://github.com/dropbox/dbxcli/pull/217 to use `WithRoot`

**Comment by AndreyVMarkelov** [comment]
Fixed on master.
The fix uses the account root namespace from users/get_current_account and applies it with the SDK’s Config.WithRoot(...), so file commands run against the correct Dropbox team-space root instead of only the member’s personal namespace.

Thanks again for pointing out that --as-member alone was not enough here.
